name: Android Build 

on:

  push:
    branches: ['master']


  pull_request:
    branches: ['master']


jobs:
  test:
    runs-on: ubuntu-lastest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/checkout@v4
      with:       
       distribution: 'temurin'
       java-verison: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permisson to Gradle wrapper
      run: chmod +x gradlew

    - name: Bulid Project 
      run: ./gradlew assembleDebug
      
    
